# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: travel_on_two_development
  host: localhost
  pool: 5
  username: evanshabsove
  password: 123

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: travel_on_two_project_test
  pool: 5
  username: evanshabsove
  password: 123

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: travel_on_two_production
  pool: 5
  username: travel_on_two_beta
  password: password

cucumber:
  <<: *TEST
