# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: travel_on_two_development
  host: localhost
  pool: 5
  username: macbookpro
  password: 123456

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: travel_on_two_project_test
  pool: 5
  username: macbookpro
  password: 123456

# production:
#   adapter: postgresql
#   encoding: utf8
#   host: localhost
#   database: travel_on_two_production
#   pool: 5
#   username: travel_on_two_beta
#   password: password
production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

cucumber:
  <<: *TEST
